---
# Playbook for Web Servers

- name: Playbook for Web Servers
  hosts: websrvr_DEV
  become: true
  tasks:
    - name: Take backup of existing index.html
      command: cp /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.bak

    - name: Copy custome index.html to web servers
      copy:
        src: "./index.html"
        dest: "/usr/share/nginx/html/index.html"

